version: "3.8"

services:
  # 1) Base de datos MySQL inicializada automáticamente
  db:
    image: mysql:8.0
    container_name: shakai-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"

  # 2) Backend Django
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: shakai-backend
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      # Deben coincidir con settings.py
      SECRET_KEY:    django-insecure-yourprodsecret
      DEBUG:         "False"
      ALLOWED_HOSTS: "localhost,127.0.0.1"
      DB_NAME:       mydb
      DB_USER:       myuser
      DB_PASSWORD:   mypassword
      DB_HOST:       db
      DB_PORT:       "3306"
    depends_on:
      db:
        condition: service_healthy
    command: >
      sh -c "
        until nc -z db 3306; do
          echo 'Esperando a MySQL…';
          sleep 2;
        done;
        python manage.py migrate &&
        python manage.py runserver 0.0.0.0:8000
      "

  # 3) Frontend React/Vite
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: shakai-frontend
    restart: on-failure
    ports:
      - "5175:5175"
    depends_on:
      - backend

volumes:
  db_data:
